### ISSUE TITLE
Beamformer observation specifics

### ISSUE THREAD

**Issue by mserylak** [rubyvanrooyen/astrokat#1]
This is placeholder for beamformer-related observation aspects:
- noise diode (modes of operations, switching cycles),
- calibrators,
- multiple targets?
- beam shaping,
- quantization settings,
- gain settings,
- how do we specify those (array, single value etc.)?
- drift scans, spider scans, spiral scans, raster scans,
- use cases (how do we observe, observing strategy),

**Comment by mserylak** [comment]
Had a chat with Willem. It seems that flux calibration is a bit of an unknown for him and to others. I think we should talk with Ben Stappers. He has experience with inferferometry and could give us a helping hand. Pretty much most of the list above is still in works. Will keep thinking.

**Comment by rubyvanrooyen** [comment]
Config and conversion updates:
* Make pool_resources as a comma separated list
* Add dump_period version for catalogue conversion + test dump_rate to make sure <1
* Add bfb noise diode key to allow switching ND on and off with a pattern per pointing
* Add on_duration to noise diode options for fbf

General comments:
* Need better comments per key and config check script after conversion
* Target naming conventions must be specified by user, will not be handled by script
* Observation types for beamformer fb_fluxcal and fb_polcal
* Need to construct SOP for using beamformer with correlator and telescope setup requirements

```
instrument:
  pool_resources: ['m011,', 'm022', 'ptuse']
  band: l
  product: c856M4k
  dump_rate: 0.5
noise_diode:
  pattern: all
  on_fraction: -1.0
  cycle_len: 0.1
observation_loop:
  - LST: 0.0-23.9
    target_list:
      - name=1934-638, radec=19:39:25.03 -63:42:45.63, tags=target, duration=120.0, type=drift_scan
      - name=0408-65, radec=04:08:20.38 -65:45:09.1, tags=target, duration=180.0
```
