### ISSUE TITLE
YAML update for solar body targets

### ISSUE THREAD

**Issue by rubyvanrooyen** [rubyvanrooyen/astrokat#12]
Tag strategy of current YAML files to allow easy specification of solar bodies

**Comment by rubyvanrooyen** [comment]
Planets as specials
```
observation_loop:
  - LST: 0.0-23.9
    target_list:
      - name=Jupiter, special=special, tags=target, duration=60.0
      - name=Moon, special=special, tags=target, duration=40.0
```

Comets as XEphem orbits
```
observation_loop:
  - LST: 20:46-16:47
    target_list:
      - name=C/2002 Y1 | C/2002 Y1 (Juels-Holvorcem), xephem=C/2002 Y1~e~103.7816~166.2194~128.8232~242.5695~0~0.9970576~0~4/13.2508/2003~1/01/2000~g6.5~4~0 , tags=solarsys target, duration=900.0
```
